/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MrEliptik (https://sketchfab.com/mreliptik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/floating-volcano-island-b2aa6c4676ab4808856ef28aa6ed8933
Title: Floating volcano island
*/

import React, { useRef,useEffect} from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame,useThree} from '@react-three/fiber'
import islandScene from'../assets/3d/island.glb'
import {a} from '@react-spring/three'

const Island = ({
  isRotating,
  setIsRotating,
  setCurrentStage,
  ...props
}) => {
  const islandRef = useRef()
  const { gl } = useThree()
const { nodes, materials } = useGLTF(islandScene)


  const rotationDirection = useRef(0) // -1 left, +1 right

  // ✅ MOUSE CONTROL
  const handlePointerDown = (e) => {
    e.stopPropagation()
    e.preventDefault()

    if (e.button === 0) {
      // Left click → rotate left
      rotationDirection.current = -1
      setIsRotating(true)
    }

    if (e.button === 2) {
      // Right click → rotate right
      rotationDirection.current = 1
      setIsRotating(true)
    }
  }

  const handlePointerUp = () => {
    setIsRotating(false)
    rotationDirection.current = 0
  }

  // ✅ KEYBOARD CONTROL
  const handleKeyDown = (e) => {
    if (e.key === 'ArrowLeft') {
      rotationDirection.current = -1
      setIsRotating(true)
    }

    if (e.key === 'ArrowRight') {
      rotationDirection.current = 1
      setIsRotating(true)
    }
  }

  const handleKeyUp = (e) => {
    if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
      setIsRotating(false)
      rotationDirection.current = 0
    }
  }

  // ✅ ROTATION LOOP
  useFrame(() => {
    if (!islandRef.current) return

    if (isRotating) {
      islandRef.current.rotation.y +=
        rotationDirection.current * 0.02
    }

    const rotation = islandRef.current.rotation.y
    const normalizedRotation =
      ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI)

    switch (true) {
      case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
        setCurrentStage?.(4)
        break
      case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
        setCurrentStage?.(3)
        break
      case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
        setCurrentStage?.(2)
        break
      case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
        setCurrentStage?.(1)
        break
      default:
        setCurrentStage?.(null)
    }
  })

  useEffect(() => {
    const canvas = gl.domElement

    // disable browser right-click menu
    canvas.oncontextmenu = (e) => e.preventDefault()

    canvas.addEventListener('pointerdown', handlePointerDown)
    canvas.addEventListener('pointerup', handlePointerUp)
    document.addEventListener('keydown', handleKeyDown)
    document.addEventListener('keyup', handleKeyUp)

    return () => {
      canvas.removeEventListener('pointerdown', handlePointerDown)
      canvas.removeEventListener('pointerup', handlePointerUp)
      document.removeEventListener('keydown', handleKeyDown)
      document.removeEventListener('keyup', handleKeyUp)
    }
  }, [gl])
  return (
    <a.group ref={islandRef}{...props}>
      <group position={[0.713, 2.473, 0.339]} rotation={[0, 0.04, 0]} scale={1.734}>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.DeepBlack}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Blank}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.Eyes}
        />
      </group>
      <group
        position={[0.05, 0.558, -0.094]}
        rotation={[-Math.PI, 0, 0]}
        scale={[2.371, 1.248, 2.371]}>
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.BaseRock}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.Sand}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Water}
        />
      </group>
      <group
        position={[-0.146, 2.176, -0.924]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1.709, 0.325, 1.709]}>
        <mesh
          geometry={nodes.Object_78.geometry}
          material={materials.VolcanoRock}
        />
        <mesh
          geometry={nodes.Object_79.geometry}
          material={materials.Grass}
        />
        <mesh
          geometry={nodes.Object_80.geometry}
          material={materials.Lava}
        />
      </group>
      <group position={[1.179, 2.535, -0.848]} scale={[0.042, 0.241, 0.042]}>
        <mesh
          geometry={nodes.Object_188.geometry}
          material={materials.TreeTrunk}
        />
        <mesh
          geometry={nodes.Object_189.geometry}
          material={materials.TreeLeaf}
        />
      </group>
      <group
        position={[2.177, 2.023, -0.281]}
        rotation={[-0.298, -0.73, -0.266]}
        scale={[0.042, 0.241, 0.042]}>
        <mesh
          geometry={nodes.Object_191.geometry}
          material={materials.TreeTrunk}
        />
        <mesh
          geometry={nodes.Object_192.geometry}
          material={materials.TreeLeaf}
        />
      </group>
      <group
        position={[-0.486, 2.043, 1.736]}
        rotation={[0.015, -1.269, 0.014]}
        scale={[0.042, 0.241, 0.042]}>
        <mesh
          geometry={nodes.Object_194.geometry}
          material={materials.TreeTrunk}
        />
        <mesh
          geometry={nodes.Object_195.geometry}
          material={materials.TreeLeaf}
        />
      </group>
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.CaveEntrance}
        position={[0.776, 2.103, 0.389]}
        rotation={[-0.047, -0.909, -1.124]}
        scale={0.321}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.Rock}
        position={[-0.999, 1.766, 0.781]}
        scale={0.302}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.Rock}
        position={[-0.642, 1.766, 0.781]}
        rotation={[-0.286, -0.186, -0.25]}
        scale={0.242}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.Rock}
        position={[0.405, 1.766, 0.742]}
        rotation={[-Math.PI, -0.834, -Math.PI]}
        scale={0.302}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.Rock}
        position={[1.07, 1.766, 0.104]}
        rotation={[0, 0.601, 0]}
        scale={0.302}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.Rock}
        position={[0.42, 2.068, 0.626]}
        rotation={[-Math.PI, 0.683, -Math.PI]}
        scale={0.128}
      />
      <mesh
        geometry={nodes.Object_24.geometry}
        material={materials.Rock}
        position={[1.05, 2.068, 0.086]}
        rotation={[2.922, 1.249, -Math.PI]}
        scale={0.128}
      />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials.Rock}
        position={[0.42, 2.217, 0.535]}
        rotation={[2.857, 1.519, -Math.PI]}
        scale={0.097}
      />
      <mesh
        geometry={nodes.Object_28.geometry}
        material={materials.Rock}
        position={[1.005, 2.217, 0.066]}
        rotation={[2.857, 1.519, -Math.PI]}
        scale={0.097}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.Rock}
        position={[0.5, 2.345, 0.481]}
        rotation={[1.068, 1.033, -1.785]}
        scale={0.076}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials.Rock}
        position={[0.922, 2.346, 0.105]}
        rotation={[0.58, 0.725, -1.661]}
        scale={0.087}
      />
      <mesh
        geometry={nodes.Object_34.geometry}
        material={materials.Rock}
        position={[0.846, 2.427, 0.165]}
        rotation={[0.03, -0.796, -1.28]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_36.geometry}
        material={materials.Rock}
        position={[0.549, 2.418, 0.405]}
        rotation={[0.645, 0.025, -1.553]}
        scale={0.068}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials.Rock}
        position={[0.761, 2.476, 0.215]}
        rotation={[-3.117, 0.168, -1.913]}
        scale={0.07}
      />
      <mesh 
        geometry={nodes.Object_40.geometry}
        material={materials.Rock}
        position={[0.596, 2.477, 0.333]}
        rotation={[0.489, -0.124, -1.66]}
        scale={0.064}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.Rock}
        position={[0.671, 2.493, 0.274]}
        rotation={[1.219, 0.704, -1.47]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials.Rock}
        position={[0.358, 2.354, 0.356]}
        rotation={[-2.94, 0.076, 2.769]}
        scale={[0.144, 0.128, 0.17]}
      />
      <mesh
        geometry={nodes.Object_46.geometry}
        material={materials.Rock}
        position={[0.638, 2.354, 0.209]}
        rotation={[0.073, -1.043, -1.361]}
        scale={[0.144, 0.133, 0.187]}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.Rock}
        position={[0.844, 2.354, 0.006]}
        rotation={[2.97, 0.891, 2.083]}
        scale={[0.185, 0.115, 0.167]}
      />
      <mesh
        geometry={nodes.Object_50.geometry}
        material={materials.Rock}
        position={[0.474, 2.501, 0.247]}
        rotation={[0.05, -0.736, -1.391]}
        scale={[0.126, 0.085, 0.181]}
      />
      <mesh
        
        
        geometry={nodes.Object_52.geometry}
        material={materials.Rock}
        position={[0.688, 2.501, 0.089]}
        rotation={[-0.516, -1.176, -1.859]}
        scale={[0.126, 0.086, 0.19]}
      />
      <mesh
        
        
        geometry={nodes.Object_54.geometry}
        material={materials.Rock}
        position={[0.208, 2.081, 0.617]}
        rotation={[-1.839, 0.1, 2.907]}
        scale={[0.144, 0.143, 0.382]}
      />
      <mesh
        
        
        geometry={nodes.Object_56.geometry}
        material={materials.Rock}
        position={[1.191, 2.125, -0.104]}
        rotation={[-1.302, -0.552, -3.111]}
        scale={[0.144, 0.143, 0.382]}
      />
      <mesh
        
        
        geometry={nodes.Object_58.geometry}
        material={materials.material_0}
        position={[1.107, 3.79, -1.136]}
        rotation={[-2.886, 1.304, 2.963]}
        scale={[0.479, 0.332, 0.364]}
      />
      <mesh
        
        
        geometry={nodes.Object_60.geometry}
        material={materials.material_0}
        position={[-2.448, 3.537, -1.485]}
        rotation={[-0.142, 1.179, 0.093]}
        scale={[0.627, 0.375, 0.38]}
      />
      <mesh
        
        
        geometry={nodes.Object_62.geometry}
        material={materials.material_0}
        position={[0.98, 3.619, -1.634]}
        rotation={[3.117, 0.939, 3.1]}
        scale={[0.305, 0.228, 0.228]}
      />
      <mesh
        
        
        geometry={nodes.Object_64.geometry}
        material={materials.material_0}
        position={[1.329, 3.694, -0.751]}
        rotation={[0.08, 1.385, -0.141]}
        scale={[0.227, 0.17, 0.17]}
      />
      <mesh
        
        
        geometry={nodes.Object_66.geometry}
        material={materials.material_0}
        position={[-2.362, 3.304, -1.345]}
        rotation={[-0.063, 0.98, 0.078]}
        scale={[0.345, 0.279, 0.267]}
      />
      <mesh
        
        
        geometry={nodes.Object_68.geometry}
        material={materials.material_0}
        position={[-2.527, 3.242, -0.997]}
        rotation={[-0.052, 0.83, 0.064]}
        scale={[0.203, 0.164, 0.157]}
      />
      <mesh
        
        
        geometry={nodes.Object_70.geometry}
        material={materials.material_0}
        position={[-2.776, 3.277, -1.165]}
        rotation={[-0.096, 1.196, 0.115]}
        scale={[0.355, 0.21, 0.253]}
      />
      <mesh
        
        
        geometry={nodes.Object_72.geometry}
        material={materials.material_0}
        position={[-2.087, 3.244, -1.786]}
        rotation={[0.02, 0.755, -0.076]}
        scale={[0.518, 0.353, 0.349]}
      />
      <mesh
        
        
        geometry={nodes.Object_74.geometry}
        material={materials.material_0}
        position={[-1.619, 3.086, 0.355]}
        rotation={[-3.009, 1.042, 3.095]}
        scale={[0.412, 0.286, 0.313]}
      />
      <mesh
        
        
        geometry={nodes.Object_76.geometry}
        material={materials.material_0}
        position={[-1.347, 3.004, 0.625]}
        rotation={[2.961, 1.488, -3.024]}
        scale={[0.196, 0.146, 0.146]}
      />
      <mesh
        
        
        geometry={nodes.Object_82.geometry}
        material={materials.Smoke}
        position={[-0.151, 4.308, -1.225]}
        scale={0.331}
      />
      <mesh
        
        
        geometry={nodes.Object_84.geometry}
        material={materials.Smoke}
        position={[-0.313, 4.312, -1.071]}
        scale={0.344}
      />
      <mesh
        
        
        geometry={nodes.Object_86.geometry}
        material={materials.Smoke}
        position={[-0.08, 4.555, -1.386]}
        rotation={[-0.152, -0.267, -0.115]}
        scale={0.368}
      />
      <mesh
        
        
        geometry={nodes.Object_88.geometry}
        material={materials.Smoke}
        position={[-0.332, 4.664, -1.27]}
        rotation={[-0.152, -0.267, -0.115]}
        scale={0.356}
      />
      <mesh
        
        
        geometry={nodes.Object_90.geometry}
        material={materials.Smoke}
        position={[-0.152, 4.841, -1.672]}
        rotation={[-0.044, -0.173, -0.025]}
        scale={0.428}
      />
      <mesh
        
        
        geometry={nodes.Object_92.geometry}
        material={materials.Smoke}
        position={[-0.439, 4.902, -1.445]}
        rotation={[-0.044, -0.173, -0.025]}
        scale={0.414}
      />
      <mesh
        
        
        geometry={nodes.Object_94.geometry}
        material={materials.Smoke}
        position={[-0.329, 5.126, -2.026]}
        rotation={[-0.044, -0.173, -0.025]}
        scale={0.634}
      />
      <mesh
        
        
        geometry={nodes.Object_96.geometry}
        material={materials.Smoke}
        position={[-0.571, 5.115, -1.695]}
        rotation={[-0.044, -0.173, -0.025]}
        scale={0.512}
      />
      <mesh
        
        
        geometry={nodes.Object_98.geometry}
        material={materials.Smoke}
        position={[-0.142, 4.73, -1.3]}
        rotation={[-0.152, -0.267, -0.115]}
        scale={0.261}
      />
      <mesh
        
        
        geometry={nodes.Object_100.geometry}
        material={materials.Smoke}
        position={[-0.169, 4.217, -1.061]}
        rotation={[-0.152, -0.267, -0.115]}
        scale={0.285}
      />
      <mesh
        
        
        geometry={nodes.Object_102.geometry}
        material={materials.Smoke}
        position={[-0.562, 5.578, -2.378]}
        rotation={[-0.2, -0.296, -0.125]}
        scale={0.796}
      />
      <mesh
        
        
        geometry={nodes.Object_104.geometry}
        material={materials.Smoke}
        position={[-0.916, 5.643, -2.01]}
        rotation={[-0.2, -0.296, -0.125]}
        scale={0.701}
      />
      <mesh
        
        
        geometry={nodes.Object_106.geometry}
        material={materials.Smoke}
        position={[-0.844, 6.147, -2.839]}
        rotation={[-0.291, -0.355, -0.188]}
        scale={1.098}
      />
      <mesh
        
        
        geometry={nodes.Object_108.geometry}
        material={materials.Smoke}
        position={[-1.355, 6.222, -2.255]}
        rotation={[-0.291, -0.355, -0.188]}
        scale={0.86}
      />
      <mesh
        
        
        geometry={nodes.Object_110.geometry}
        material={materials.Smoke}
        position={[-0.788, 6.126, -2.205]}
        rotation={[-0.2, -0.296, -0.125]}
        scale={0.68}
      />
      <mesh
        
        
        geometry={nodes.Object_112.geometry}
        material={materials.Smoke}
        position={[-0.456, 5.306, -1.93]}
        rotation={[-0.044, -0.173, -0.025]}
        scale={0.57}
      />
      <mesh
        
        
        geometry={nodes.Object_114.geometry}
        material={materials.Smoke}
        position={[-0.692, 5.707, -2.013]}
        rotation={[-0.044, -0.173, -0.025]}
        scale={0.57}
      />
      <mesh
        
        
        geometry={nodes.Object_116.geometry}
        material={materials.Lava}
        position={[0.281, 4.238, -0.574]}
        rotation={[2.65, 0.412, -1.23]}
        scale={0.046}
      />
      <mesh
        
        
        geometry={nodes.Object_118.geometry}
        material={materials.Lava}
        position={[0.462, 4.29, -0.648]}
        rotation={[2.65, 0.412, -1.23]}
        scale={0.039}
      />
      <mesh
        
        
        geometry={nodes.Object_120.geometry}
        material={materials.Lava}
        position={[0.184, 4.251, -0.628]}
        rotation={[2.65, 0.412, -1.23]}
        scale={[0.038, 0.028, 0.038]}
      />
      <mesh
        
        
        geometry={nodes.Object_122.geometry}
        material={materials.Lava}
        position={[0.189, 4.325, -0.666]}
        rotation={[2.65, 0.412, -1.23]}
        scale={[0.038, 0.04, 0.038]}
      />
      <mesh
        
        
        geometry={nodes.Object_124.geometry}
        material={materials.Lava}
        position={[0.039, 4.31, -0.536]}
        rotation={[-0.491, -0.288, -0.162]}
        scale={[0.039, 0.041, 0.052]}
      />
      <mesh
        
        
        geometry={nodes.Object_126.geometry}
        material={materials.Lava}
        position={[0.145, 4.46, -0.45]}
        rotation={[-0.491, -0.288, -0.162]}
        scale={[0.042, 0.042, 0.041]}
      />
      <mesh
        
        
        geometry={nodes.Object_128.geometry}
        material={materials.Lava}
        position={[0.022, 4.211, -0.488]}
        rotation={[-0.491, -0.288, -0.162]}
        scale={[0.038, 0.028, 0.038]}
      />
      <mesh
        
        
        geometry={nodes.Object_130.geometry}
        material={materials.Lava}
        position={[0.093, 4.189, -0.453]}
        rotation={[-0.491, -0.288, -0.162]}
        scale={[0.037, 0.038, 0.036]}
      />
      <mesh
        
        
        geometry={nodes.Object_132.geometry}
        material={materials.Lava}
        position={[-0.131, 4.084, -0.719]}
        rotation={[-3.049, -0.017, -1.324]}
        scale={0.038}
      />
      <mesh
        
        
        geometry={nodes.Object_134.geometry}
        material={materials.Lava}
        position={[0.008, 4.189, -0.822]}
        rotation={[-3.049, -0.017, -1.324]}
        scale={[0.051, 0.042, 0.052]}
      />
      <mesh
        
        
        geometry={nodes.Object_136.geometry}
        material={materials.Lava}
        position={[-0.24, 4.111, -0.714]}
        rotation={[-3.049, -0.017, -1.324]}
        scale={[0.038, 0.028, 0.038]}
      />
      <mesh
        
        
        geometry={nodes.Object_138.geometry}
        material={materials.Lava}
        position={[-0.242, 4.193, -0.707]}
        rotation={[-3.049, -0.017, -1.324]}
        scale={[0.038, 0.04, 0.038]}
      />
      <mesh
        
        
        geometry={nodes.Object_140.geometry}
        material={materials.Lava}
        position={[-0.178, 4.193, -0.456]}
        rotation={[0.081, 0.141, -0.067]}
        scale={[0.043, 0.043, 0.04]}
      />
      <mesh
        
        
        geometry={nodes.Object_142.geometry}
        material={materials.Lava}
        position={[-0.257, 3.958, -0.576]}
        rotation={[0.081, 0.141, -0.067]}
        scale={[0.044, 0.046, 0.044]}
      />
      <mesh
        
        
        geometry={nodes.Object_144.geometry}
        material={materials.Lava}
        position={[-0.431, 4.217, -0.564]}
        rotation={[0.292, -0.665, 1.332]}
        scale={[0.063, 0.057, 0.055]}
      />
      <mesh
        
        
        geometry={nodes.Object_146.geometry}
        material={materials.Lava}
        position={[-0.57, 4.358, -0.481]}
        rotation={[0.292, -0.665, 1.332]}
        scale={[0.068, 0.059, 0.057]}
      />
      <mesh
        
        
        geometry={nodes.Object_148.geometry}
        material={materials.Lava}
        position={[-0.306, 4.235, -0.457]}
        rotation={[0.292, -0.665, 1.332]}
        scale={[0.056, 0.044, 0.039]}
      />
      <mesh
        
        
        geometry={nodes.Object_150.geometry}
        material={materials.Lava}
        position={[-0.171, 4.15, -0.594]}
        rotation={[-2.771, 0.56, -2.77]}
        scale={[0.044, 0.043, 0.043]}
      />
      <mesh
        
        
        geometry={nodes.Object_152.geometry}
        material={materials.Lava}
        position={[-0.178, 4.352, -0.668]}
        rotation={[-2.771, 0.56, -2.77]}
        scale={0.037}
      />
      <mesh
        
        
        geometry={nodes.Object_154.geometry}
        material={materials.Lava}
        position={[-0.029, 4.019, -0.597]}
        rotation={[2.619, -0.017, -1.324]}
        scale={[0.087, 0.043, 0.039]}
      />
      <mesh
        
        
        geometry={nodes.Object_156.geometry}
        material={materials.Lava}
        position={[-0.042, 3.955, -0.587]}
        rotation={[2.634, 0.132, -1.586]}
        scale={[0.087, 0.043, 0.039]}
      />
      <mesh
        
        
        geometry={nodes.Object_158.geometry}
        material={materials.Lava}
        position={[-0.032, 3.883, -0.575]}
        rotation={[2.634, 0.132, -1.586]}
        scale={[0.087, 0.043, 0.039]}
      />
      <mesh
        
        
        geometry={nodes.Object_160.geometry}
        material={materials.Grass}
        position={[0.944, 2.366, -0.419]}
        rotation={[0.185, 0.449, 0.168]}
        scale={0.183}
      />
      <mesh
        
        
        geometry={nodes.Object_162.geometry}
        material={materials.Grass}
        position={[0.959, 2.363, -0.676]}
        rotation={[-0.035, 0.453, 0.04]}
        scale={0.111}
      />
      <mesh
        
        
        geometry={nodes.Object_164.geometry}
        material={materials.Grass}
        position={[0.193, 2.328, 0.182]}
        rotation={[-1.171, -0.076, -1.089]}
        scale={0.12}
      />
      <mesh
        
        
        geometry={nodes.Object_166.geometry}
        material={materials.Grass}
        position={[-0.143, 2.331, 0.182]}
        rotation={[-0.406, -0.015, -0.317]}
        scale={0.163}
      />
      <mesh
        
        
        geometry={nodes.Object_168.geometry}
        material={materials.Grass}
        position={[0.734, 2.336, -0.255]}
        rotation={[-1.896, 0.255, -1.293]}
        scale={0.147}
      />
      <mesh
        
        
        geometry={nodes.Object_170.geometry}
        material={materials.Grass}
        position={[0.047, 2.352, 0.231]}
        rotation={[-0.405, -0.012, -0.313]}
        scale={0.077}
      />
      <mesh
        
        
        geometry={nodes.Object_172.geometry}
        material={materials.Grass}
        position={[0.241, 3.396, -0.437]}
        rotation={[-2.208, 0.374, 2.783]}
        scale={0.055}
      />
      <mesh
        
        
        geometry={nodes.Object_174.geometry}
        material={materials.Grass}
        position={[0.324, 3.397, -0.495]}
        rotation={[-2.613, -0.671, -3.104]}
        scale={0.072}
      />
      <mesh
        
        
        geometry={nodes.Object_176.geometry}
        material={materials.Grass}
        position={[0.399, 3.388, -0.529]}
        rotation={[-2.613, -0.674, -3.1]}
        scale={0.043}
      />
      <mesh
        
        
        geometry={nodes.Object_178.geometry}
        material={materials.Grass}
        position={[0.437, 3.395, -0.871]}
        rotation={[1.371, 0.682, -0.131]}
        scale={0.094}
      />
      <mesh
        
        
        geometry={nodes.Object_180.geometry}
        material={materials.Grass}
        position={[0.474, 3.4, -0.992]}
        rotation={[-0.455, 0.088, -0.046]}
        scale={0.067}
      />
      <mesh
        
        
        geometry={nodes.Object_182.geometry}
        material={materials.Grass}
        position={[-0.152, 3.392, -0.374]}
        rotation={[-1.171, -0.076, -1.089]}
        scale={0.102}
      />
      <mesh
        
        
        geometry={nodes.Object_184.geometry}
        material={materials.Grass}
        position={[0.869, 2.391, -1.411]}
        rotation={[2.999, -0.88, 3.022]}
        scale={0.183}
      />
      <mesh
        
        
        geometry={nodes.Object_186.geometry}
        material={materials.Grass}
        position={[0.993, 2.375, -1.164]}
        rotation={[-3.091, -0.899, -3.077]}
        scale={0.111}
      />
    </a.group>
  );
};

export default Island;
